Add image_transport camera transporter
robomaster-oss/rmoss_core pull request #37
Opened 2023-03-27 05:23 UTC by Ericsii

#36

2023-04-04 12:36 UTC, gezp commented on rmoss_cam/src/cam_server.cpp
> +      camera_name_ + "/camera_info", 10);
这个就不需要了吧，如果有需求，直接使用use_image_transport_camera_publisher 就满足了。

2023-04-04 12:36 UTC, gezp commented on rmoss_cam/src/cam_server.cpp
> +      camera_name_ + "/camera_info", 10);
这个就不需要了吧，如果有需求，直接使用use_image_transport_camera_publisher 就满足了。

2023-04-09 04:26 UTC, Ericsii commented on rmoss_cam/src/cam_server.cpp
> +      camera_name_ + "/camera_info", 10);
已修改

2023-04-09 04:43 UTC, gezp requested changes

2023-04-09 04:43 UTC, gezp commented on rmoss_cam/src/cam_server.cpp
> +    auto cam_info_period_ms = std::chrono::milliseconds(static_cast<int64_t>(1000.0 / 10));
这一行代码没用到，可以删掉

2023-04-09 04:44 UTC, gezp requested changes

2023-04-09 04:44 UTC, gezp commented on rmoss_cam/src/cam_server.cpp
> +  std::function<void()> cam_info_callback;
没用到的变量

2023-04-09 05:53 UTC, gezp approved these changes
LGTM

2023-04-09 05:53 UTC, merged